In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/marketing_campaign.csv")

df.head()

,CampaignID,StartDate,EndDate,Channel,Impressions,Clicks,Leads,Conversions,Cost_USD,Revenue_USD,ROI
0,CAMP00001,2025-04-13,2025-04-19,Search,293520,23335,11643,5389,1052.39,2236.02,1.12
1,CAMP00002,2025-12-15,2025-12-24,Search,200340,15841,6601,2498,3964.90,11740.15,1.96
2,CAMP00003,2025-09-28,2025-10-06,Email,239365,16478,8043,3397,1000.39,1902.24,0.90
3,CAMP00004,2025-04-17,2025-04-30,Search,156382,2672,1014,342,1252.63,2209.74,0.76
4,CAMP00005,2025-03-13,2025-03-22,Influencer,285472,4155,1521,565,4935.48,14111.31,1.86

In [2]:
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (10000, 11)

Columns:
['CampaignID', 'StartDate', 'EndDate', 'Channel', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Cost_USD', 'Revenue_USD', 'ROI']

Data Types:
CampaignID      object
StartDate       object
EndDate         object
Channel         object
Impressions      int64
Clicks           int64
Leads            int64
Conversions      int64
Cost_USD       float64
Revenue_USD    float64
ROI            float64
dtype: object

In [3]:
print("Missing Values:\n")
print(df.isnull().sum())

Missing Values:

CampaignID     0
StartDate      0
EndDate        0
Channel        0
Impressions    0
Clicks         0
Leads          0
Conversions    0
Cost_USD       0
Revenue_USD    0
ROI            0
dtype: int64

In [4]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [6]:
df["StartDate"] = pd.to_datetime(df["StartDate"])
df["EndDate"] = pd.to_datetime(df["EndDate"])

In [7]:
# Campaign Duration
df["Campaign_Duration"] = (
    df["EndDate"] - df["StartDate"]
).dt.days

# Cost Per Click
df["CPC"] = df["Cost_USD"] / df["Clicks"]

# Cost Per Lead
df["CPL"] = df["Cost_USD"] / df["Leads"]

# Conversion Rate
df["Conversion_Rate"] = (
    df["Conversions"] / df["Clicks"]
) * 100

df.head()

,CampaignID,StartDate,EndDate,Channel,Impressions,Clicks,Leads,Conversions,Cost_USD,Revenue_USD,ROI,Campaign_Duration,CPC,CPL,Conversion_Rate
0,CAMP00001,2025-04-13,2025-04-19,Search,293520,23335,11643,5389,1052.39,2236.02,1.12,6,0.045099,0.090388,23.094065
1,CAMP00002,2025-12-15,2025-12-24,Search,200340,15841,6601,2498,3964.90,11740.15,1.96,9,0.250294,0.600651,15.769206
2,CAMP00003,2025-09-28,2025-10-06,Email,239365,16478,8043,3397,1000.39,1902.24,0.90,8,0.060711,0.124380,20.615366
3,CAMP00004,2025-04-17,2025-04-30,Search,156382,2672,1014,342,1252.63,2209.74,0.76,13,0.468799,1.235335,12.799401
4,CAMP00005,2025-03-13,2025-03-22,Influencer,285472,4155,1521,565,4935.48,14111.31,1.86,9,1.187841,3.244892,13.598075

In [8]:
df.to_csv(
    "../data/processed/marketing_campaign_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [9]:
df.isnull().sum()

CampaignID           0
StartDate            0
EndDate              0
Channel              0
Impressions          0
Clicks               0
Leads                0
Conversions          0
Cost_USD             0
Revenue_USD          0
ROI                  0
Campaign_Duration    0
CPC                  0
CPL                  0
Conversion_Rate      0
dtype: int64