# Data Modeling

## Objective

Prepare the marketing dataset for business intelligence reporting by understanding the relationship between business entities and creating a structured analytical model.

## Business Goal

Build a clean analytical dataset that supports KPI reporting and dashboard development.

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/marketing_campaign_cleaned.csv")

df.head()

,CampaignID,StartDate,EndDate,Channel,Impressions,Clicks,Leads,Conversions,Cost_USD,Revenue_USD,ROI,Campaign_Duration,CPC,CPL,Conversion_Rate
0,CAMP00001,2025-04-13,2025-04-19,Search,293520,23335,11643,5389,1052.39,2236.02,1.12,6,0.045099,0.090388,23.094065
1,CAMP00002,2025-12-15,2025-12-24,Search,200340,15841,6601,2498,3964.90,11740.15,1.96,9,0.250294,0.600651,15.769206
2,CAMP00003,2025-09-28,2025-10-06,Email,239365,16478,8043,3397,1000.39,1902.24,0.90,8,0.060711,0.124380,20.615366
3,CAMP00004,2025-04-17,2025-04-30,Search,156382,2672,1014,342,1252.63,2209.74,0.76,13,0.468799,1.235335,12.799401
4,CAMP00005,2025-03-13,2025-03-22,Influencer,285472,4155,1521,565,4935.48,14111.31,1.86,9,1.187841,3.244892,13.598075

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CampaignID         10000 non-null  object
 1   StartDate          10000 non-null  object
 2   EndDate            10000 non-null  object
 3   Channel            10000 non-null  object
 4   Impressions        10000 non-null  int64
 5   Clicks             10000 non-null  int64
 6   Leads              10000 non-null  int64
 7   Conversions        10000 non-null  int64
 8   Cost_USD           10000 non-null  float64
 9   Revenue_USD        10000 non-null  float64
 10  ROI                10000 non-null  float64
 11  Campaign_Duration  10000 non-null  int64
 12  CPC                10000 non-null  float64
 13  CPL                10000 non-null  float64
 14  Conversion_Rate    10000 non-null  float64
dtypes: float64(6), int64(5), object(4)
memory usage: 1.1+ MB

In [3]:
df.dtypes

CampaignID            object
StartDate             object
EndDate               object
Channel               object
Impressions            int64
Clicks                 int64
Leads                  int64
Conversions            int64
Cost_USD             float64
Revenue_USD          float64
ROI                  float64
Campaign_Duration      int64
CPC                  float64
CPL                  float64
Conversion_Rate      float64
dtype: object

In [4]:
summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values
})

summary

               Column Data Type  Missing Values
0          CampaignID    object               0
1           StartDate    object               0
2             EndDate    object               0
3             Channel    object               0
4         Impressions     int64               0
5              Clicks     int64               0
6               Leads     int64               0
7         Conversions     int64               0
8            Cost_USD   float64               0
9         Revenue_USD   float64               0
10                ROI   float64               0
11  Campaign_Duration     int64               0
12                CPC   float64               0
13                CPL   float64               0
14    Conversion_Rate   float64               0

In [5]:
summary.to_csv("../reports/data_model_summary.csv", index=False)

print("Data Model Summary saved successfully!")

Data Model Summary saved successfully!